/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 15
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_prefix_line = 1,
  sym_blank_line = 2,
  sym_unknown_line = 3,
  anon_sym_LT = 4,
  anon_sym_GT_LBRACK = 5,
  anon_sym_RBRACK_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_SPACE = 8,
  anon_sym_COLON = 9,
  anon_sym_UTC_SEMIandroidtime = 10,
  anon_sym_LF = 11,
  sym_priority = 12,
  sym_rel_time = 13,
  sym_cpu_info = 14,
  sym_thread_name = 15,
  sym_thread_prefix = 16,
  sym_tagged_info = 17,
  sym_android_timestamp = 18,
  sym_message = 19,
  sym_source_file = 20,
  sym_line = 21,
  sym_time_anchor_line = 22,
  sym_regular_line = 23,
  sym_message_line = 24,
  aux_sym_source_file_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_prefix_line] = "prefix_line",
  [sym_blank_line] = "blank_line",
  [sym_unknown_line] = "unknown_line",
  [anon_sym_LT] = "<",
  [anon_sym_GT_LBRACK] = ">[",
  [anon_sym_RBRACK_LBRACK] = "][",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SPACE] = " ",
  [anon_sym_COLON] = ": ",
  [anon_sym_UTC_SEMIandroidtime] = " UTC;android time ",
  [anon_sym_LF] = "\n",
  [sym_priority] = "priority",
  [sym_rel_time] = "rel_time",
  [sym_cpu_info] = "cpu_info",
  [sym_thread_name] = "thread_name",
  [sym_thread_prefix] = "thread_prefix",
  [sym_tagged_info] = "tagged_info",
  [sym_android_timestamp] = "android_timestamp",
  [sym_message] = "message",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_time_anchor_line] = "time_anchor_line",
  [sym_regular_line] = "regular_line",
  [sym_message_line] = "message_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_prefix_line] = sym_prefix_line,
  [sym_blank_line] = sym_blank_line,
  [sym_unknown_line] = sym_unknown_line,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_LBRACK] = anon_sym_GT_LBRACK,
  [anon_sym_RBRACK_LBRACK] = anon_sym_RBRACK_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_UTC_SEMIandroidtime] = anon_sym_UTC_SEMIandroidtime,
  [anon_sym_LF] = anon_sym_LF,
  [sym_priority] = sym_priority,
  [sym_rel_time] = sym_rel_time,
  [sym_cpu_info] = sym_cpu_info,
  [sym_thread_name] = sym_thread_name,
  [sym_thread_prefix] = sym_thread_prefix,
  [sym_tagged_info] = sym_tagged_info,
  [sym_android_timestamp] = sym_android_timestamp,
  [sym_message] = sym_message,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_time_anchor_line] = sym_time_anchor_line,
  [sym_regular_line] = sym_regular_line,
  [sym_message_line] = sym_message_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UTC_SEMIandroidtime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_time] = {
    .visible = true,
    .named = true,
  },
  [sym_cpu_info] = {
    .visible = true,
    .named = true,
  },
  [sym_thread_name] = {
    .visible = true,
    .named = true,
  },
  [sym_thread_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_info] = {
    .visible = true,
    .named = true,
  },
  [sym_android_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_time_anchor_line] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_line] = {
    .visible = true,
    .named = true,
  },
  [sym_message_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(62);
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '<') ADVANCE(66);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '<') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(2);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(76);
      if (lookahead == ' ') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        ' ', 10,
        '-', 21,
        ':', 12,
        '<', 66,
        '>', 32,
        'U', 30,
        '[', 34,
        ']', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '<') ADVANCE(66);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(74);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(55);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(56);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 28:
      if (lookahead == ';') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'C') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 32:
      if (lookahead == '[') ADVANCE(68);
      END_STATE();
    case 33:
      if (lookahead == '[') ADVANCE(69);
      END_STATE();
    case 34:
      if (lookahead == ']') ADVANCE(97);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 35:
      if (lookahead == ']') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 37:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 42:
      if (lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 47:
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(52);
      END_STATE();
    case 48:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 61:
      if (eof) ADVANCE(62);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '<') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(2);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_prefix_line);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(2);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_unknown_line);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_GT_LBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACK_LBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == '[') ADVANCE(69);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(76);
      if (lookahead == ' ') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_UTC_SEMIandroidtime);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == '[') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(92);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(76);
      if (lookahead == ' ') ADVANCE(72);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '-') ADVANCE(55);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_priority);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_rel_time);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_cpu_info);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_cpu_info);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_thread_name);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ':') ADVANCE(94);
      if (lookahead == ']') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_thread_name);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ':') ADVANCE(94);
      if (lookahead == ']') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_thread_name);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == ':') ADVANCE(95);
      if (lookahead == '[') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_thread_name);
      if (lookahead == ':') ADVANCE(95);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_thread_name);
      if (lookahead == ':') ADVANCE(95);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_thread_prefix);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_thread_prefix);
      if (lookahead == '\n') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_thread_prefix);
      if (lookahead == '\n') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tagged_info);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '[') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tagged_info);
      if (lookahead == '[') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_android_timestamp);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ']') ADVANCE(96);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == ':') ADVANCE(104);
      if (lookahead == '[') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '\n') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '[') ADVANCE(99);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_message);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 61},
  [2] = {.lex_state = 61},
  [3] = {.lex_state = 61},
  [4] = {.lex_state = 61},
  [5] = {.lex_state = 61},
  [6] = {.lex_state = 61},
  [7] = {.lex_state = 100},
  [8] = {.lex_state = 61},
  [9] = {.lex_state = 61},
  [10] = {.lex_state = 61},
  [11] = {.lex_state = 61},
  [12] = {.lex_state = 61},
  [13] = {.lex_state = 61},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 101},
  [17] = {.lex_state = 102},
  [18] = {.lex_state = 31},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 31},
  [21] = {.lex_state = 103},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 31},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 31},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 35},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 31},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 35},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 48},
  [37] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_prefix_line] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_UTC_SEMIandroidtime] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [sym_rel_time] = ACTIONS(1),
    [sym_tagged_info] = ACTIONS(1),
    [sym_android_timestamp] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_line] = STATE(2),
    [sym_time_anchor_line] = STATE(10),
    [sym_regular_line] = STATE(10),
    [sym_message_line] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_prefix_line] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(3),
    [sym_unknown_line] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    ACTIONS(3), 3,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
    STATE(10), 3,
      sym_time_anchor_line,
      sym_regular_line,
      sym_message_line,
  [21] = 5,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(14), 1,
      anon_sym_LT,
    STATE(3), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
    STATE(10), 3,
      sym_time_anchor_line,
      sym_regular_line,
      sym_message_line,
  [42] = 2,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [52] = 2,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [62] = 2,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [72] = 5,
    ACTIONS(29), 1,
      anon_sym_LF,
    ACTIONS(31), 1,
      sym_thread_name,
    ACTIONS(33), 1,
      sym_thread_prefix,
    ACTIONS(35), 1,
      sym_tagged_info,
    ACTIONS(37), 1,
      sym_message,
  [88] = 2,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [98] = 2,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [108] = 2,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [118] = 2,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [128] = 2,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [138] = 2,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 4,
      sym_prefix_line,
      sym_blank_line,
      sym_unknown_line,
      anon_sym_LT,
  [148] = 2,
    ACTIONS(63), 1,
      sym_tagged_info,
    ACTIONS(65), 1,
      sym_android_timestamp,
  [155] = 2,
    ACTIONS(67), 1,
      anon_sym_SPACE,
    ACTIONS(69), 1,
      anon_sym_LF,
  [162] = 2,
    ACTIONS(71), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      sym_message,
  [169] = 2,
    ACTIONS(75), 1,
      sym_tagged_info,
    ACTIONS(77), 1,
      sym_message,
  [176] = 1,
    ACTIONS(79), 1,
      sym_android_timestamp,
  [180] = 1,
    ACTIONS(81), 1,
      anon_sym_GT_LBRACK,
  [184] = 1,
    ACTIONS(83), 1,
      sym_rel_time,
  [188] = 1,
    ACTIONS(85), 1,
      sym_message,
  [192] = 1,
    ACTIONS(87), 1,
      anon_sym_LF,
  [196] = 1,
    ACTIONS(89), 1,
      anon_sym_RBRACK_LBRACK,
  [200] = 1,
    ACTIONS(91), 1,
      anon_sym_LF,
  [204] = 1,
    ACTIONS(93), 1,
      sym_android_timestamp,
  [208] = 1,
    ACTIONS(95), 1,
      anon_sym_UTC_SEMIandroidtime,
  [212] = 1,
    ACTIONS(97), 1,
      anon_sym_LF,
  [216] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [220] = 1,
    ACTIONS(101), 1,
      sym_cpu_info,
  [224] = 1,
    ACTIONS(103), 1,
      anon_sym_UTC_SEMIandroidtime,
  [228] = 1,
    ACTIONS(105), 1,
      sym_android_timestamp,
  [232] = 1,
    ACTIONS(107), 1,
      anon_sym_COLON,
  [236] = 1,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
  [240] = 1,
    ACTIONS(111), 1,
      anon_sym_LF,
  [244] = 1,
    ACTIONS(113), 1,
      anon_sym_LF,
  [248] = 1,
    ACTIONS(115), 1,
      sym_priority,
  [252] = 1,
    ACTIONS(117), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 62,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 88,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 118,
  [SMALL_STATE(12)] = 128,
  [SMALL_STATE(13)] = 138,
  [SMALL_STATE(14)] = 148,
  [SMALL_STATE(15)] = 155,
  [SMALL_STATE(16)] = 162,
  [SMALL_STATE(17)] = 169,
  [SMALL_STATE(18)] = 176,
  [SMALL_STATE(19)] = 180,
  [SMALL_STATE(20)] = 184,
  [SMALL_STATE(21)] = 188,
  [SMALL_STATE(22)] = 192,
  [SMALL_STATE(23)] = 196,
  [SMALL_STATE(24)] = 200,
  [SMALL_STATE(25)] = 204,
  [SMALL_STATE(26)] = 208,
  [SMALL_STATE(27)] = 212,
  [SMALL_STATE(28)] = 216,
  [SMALL_STATE(29)] = 220,
  [SMALL_STATE(30)] = 224,
  [SMALL_STATE(31)] = 228,
  [SMALL_STATE(32)] = 232,
  [SMALL_STATE(33)] = 236,
  [SMALL_STATE(34)] = 240,
  [SMALL_STATE(35)] = 244,
  [SMALL_STATE(36)] = 248,
  [SMALL_STATE(37)] = 252,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [14] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_line, 11, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_line, 11, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_anchor_line, 15, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_time_anchor_line, 15, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_line, 12, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_line, 12, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 8, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 8, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 9, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 9, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 10, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 10, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 11, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 11, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_anchor_line, 14, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_time_anchor_line, 14, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_klog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "klog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
